parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectNamespace: '%env(PROJECT_NAMESPACE)%'

    SprykerSdk\SprykerFeatureRemover\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/Dto'
            - '../src/Event'

    _instanceof:
        SprykerSdk\SprykerFeatureRemover\ActionsActionInterface:
            tags: ['action.post-remove']

    SprykerSdk\SprykerFeatureRemover\Command\RemovePackagesCommand:
        tags: ['console.command']

    SprykerSdk\SprykerFeatureRemover\EventSubscriber\AfterPackageRemovedEventSubscriber:
        arguments:
            - !tagged_iterator action.post-remove