parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    SprykerSdk\SprykerFeatureRemover\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    SprykerSdk\SprykerFeatureRemover\Command\RemovePackagesCommand:
        tags: ['console.command']